### ISSUE TITLE
JIT assertion failure in coreclr tests

### ISSUE THREAD

**Issue by BruceForstall** [LLITCHEV/coreclr#17]
When this test -- bin/tests/Windows_NT.x64.Debug/./JIT/SIMD/CircleInConvex.exe -- is run on Linux, I see:

Assert failure(PID 5220 [0x00001464], Thread: 5220 [0x1464]): Assertion failed 'curArgTabEntry->regNum == regNum' in 'System.Collections.Generic.ArraySortHelper`1[Vector2][System.Numerics.Vector2]:PickPivotAndPartition(ref,int,int,ref):int' (IL size 131)

```
File: src/jit/morph.cpp Line: 1290
```

**Comment by LLITCHEV** [comment]
Fixed few days ago.
