### ISSUE TITLE
jumper4.il, jumper5.il tests fail

### ISSUE THREAD

**Issue by BruceForstall** [LLITCHEV/coreclr#2]
These tests fail:

JIT/Methodical/VT/callconv/_il_dbgjumper4.exe
JIT/Methodical/VT/callconv/_il_dbgjumper5.exe
JIT/Methodical/VT/callconv/_il_reljumper4.exe
JIT/Methodical/VT/callconv/_il_reljumper5.exe

These do a lot of struct passing. The precise cause of failure hasn't been investigated.

**Comment by LLITCHEV** [comment]
Checked in a fix.
